services:
    api.command.clear_cache:
        class: RestOnPhp\Command\ClearCacheCommand
        calls:
            - ['setCacheDir', [ '%cache_dir%' ]]
        tags: [ 'command' ]

    api.command.create_user:
        class: RestOnPhp\Command\CreateUserCommand
        calls:
            - ['setEntityManager', [ '@doctrine.orm.entity_manager' ]]
            - ['setUserEntity', [ '%user_entity%' ]]
        tags: [ 'command' ]
