services:
    api.handler.collection:
        class: RestOnPhp\Handler\CollectionHandler
        arguments: [ '@doctrine.orm.entity_manager', '@api.metadata.xml', !tagged api.filters.default, '@api.request.stack' ]
        public: true

    api.handler.item:
        class: RestOnPhp\Handler\ItemHandler
        arguments: [ '@symfony.serializer', '@doctrine.orm.entity_manager', '@symfony.validator', '@api.metadata.xml', !tagged api.filters.default, !tagged api.autofillers.default, '@api.request.stack' ]
        public: true

    api.handler.docs:
        class: RestOnPhp\Handler\DocsHandler
        arguments: [ '@api.metadata.xml' ]
        public: true

    api.handler.auth:
        class: RestOnPhp\Handler\AuthHandler
        arguments: [ '@symfony.serializer', '@doctrine.orm.entity_manager', '%jwt_secret%', '%user_entity%', '@api.request.stack' ]
        public: true
