services:
    api.logger.formatter.json:
        class: Monolog\Formatter\JsonFormatter
        tags: [ 'api.logger.formatter' ]

    api.logger.handler.stream:
        class: Monolog\Handler\StreamHandler
        arguments: [ '%log_dir%/app.log', 200 ]
        calls:
            - [ 'setFormatter', [ '@api.logger.formatter.json' ] ]
        tags: [ 'api.logger.handler' ]

    api.logger:
        class: Monolog\Logger
        arguments: [ 'api' ]
        public: true
