services:
    api.security.session_storage:
        class: RestOnPhp\Session\JwtSessionStorage
        public: true

    api.security.token_extractor:
        class: RestOnPhp\Token\Extractor
        public: true
        arguments: [ '%token_bearer%', '%token_key%' ]

    api.security.authorization:
        class: RestOnPhp\Security\Authorization
        arguments: [ '@api.metadata.xml',  '@api.security.token_extractor', '@api.handler.auth', '@api.security.session_storage', '@api.logger' ]
        public: true