services:
    symfony.serializer.encoder.xml_encoder:
        class: Symfony\Component\Serializer\Encoder\XmlEncoder
        tags: [ symfony.serializer.encoders ]

    symfony.serializer.encoder.json_encoder:
        class: Symfony\Component\Serializer\Encoder\JsonEncoder
        tags: [ name: symfony.serializer.encoders ]

    symfony.serializer.normalizer.object:
        class: Symfony\Component\Serializer\Normalizer\ObjectNormalizer
        tags: [ name: symfony.serializer.normalizers ]

    symfony.serializer.denormalizer.array:
        class: Symfony\Component\Serializer\Normalizer\ArrayDenormalizer
        tags: [ name: symfony.serializer.normalizers ]

    symfony.serializer.normalizer.datetime:
        class: Symfony\Component\Serializer\Normalizer\DateTimeNormalizer
        arguments: [ datetime_format: 'Y-m-d H:i:s O' ]
        tags: [ name: symfony.serializer.normalizers ]

    symfony.serializer.normalizer.entity:
        class: RestOnPhp\Normalizer\EntityNormalizer
        arguments: [ [], '@api.metadata.xml', '@doctrine.orm.entity_manager' ]
        tags: [ name: symfony.serializer.normalizers ]
    
    symfony.serializer:
        class: Symfony\Component\Serializer\Serializer
        arguments: [ [ '@symfony.serializer.normalizer.datetime', '@symfony.serializer.normalizer.entity', '@symfony.serializer.normalizer.object', '@symfony.serializer.denormalizer.array' ], [ '@symfony.serializer.encoder.xml_encoder', '@symfony.serializer.encoder.json_encoder' ] ]
