imports:
    - { resource: services/*.yml }

services:
    doctrine.factory.entity_manager:
        class: RestOnPhp\Factory\DoctrineEntityManagerFactory
        arguments: [  ]

    doctrine.orm.entity_manager:
        class: Doctrine\ORM\EntityManager
        factory: [ '@doctrine.factory.entity_manager', create]
        arguments:
            - '%database_host%'
            - '%database_port%'
            - '%database_name%'
            - '%database_user%'
            - '%database_password%'
            - '%project_dir%/config'
            - '%cache_dir%'
            - '%entity_namespace%'

    api.session.storage:
        class: RestOnPhp\Session\JwtSessionStorage
        public: true
    
    api.request.stack:
        class: Symfony\Component\HttpFoundation\RequestStack
        public: true
    
    api.token.extractor:
        class: RestOnPhp\Token\Extractor
        public: true
        arguments: [ '%token_bearer%', '%token_key%' ]

    api.metadata.xml:
        class: RestOnPhp\Metadata\XmlMetadata
        arguments: [ '%config_dir%/resources.xml', '%cache_dir%' ]
        public: true

    symfony.validator:
        class: Symfony\Component\Validator\Validator\RecursiveValidator
        factory: [ '@symfony.validator_builder', getValidator]

    symfony.validator_builder:
        class: Symfony\Component\Validator\ValidatorBuilder
        factory: [ 'Symfony\Component\Validator\Validation', createValidatorBuilder]
        calls:
            - [addXmlMapping, ['%project_dir%/config/validation.xml']]